# Purpose:
- notebook to check contents of metadata

In [23]:
import numpy as np
import pandas as pd
import mat73
import h5py
import xarray as xr
from pathlib import Path
import os
from pprint import pprint

base_dir = Path(r'E:\TPM\JK\h5')

# Cellpose results

In [7]:
mouse = 25
plane = 1
session = 4
plane_dir = base_dir / f'{mouse:03}/plane_{plane}'
roi_dir = plane_dir / f'{session:03}/plane0/roi'
pprint(os.listdir(roi_dir))

['final_mask.npy',
 'final_roi_results_025_plane_1_004_wo_dendrite_filtering.npy',
 'Fneu_reduced.npy',
 'F_reduced.npy',
 'glm',
 'iscell.npy',
 'merged_masks_025_plane_1_004.npy',
 'num_rois_025_plane_1_004.npy',
 'num_unique_rois_025_plane_1_004.npy',
 'ops.npy',
 'reduced_frame_time.pkl',
 'refined_frame_time.pkl',
 'spks_reduced.npy',
 'stat.npy',
 'stat_reduced.npy',
 'stat_refined.npy',
 'touch_tuning']


In [8]:
final_mask = np.load(roi_dir / 'final_mask.npy')

In [9]:
final_mask.shape

(387, 687, 134)

In [14]:
np.unique(final_mask[:,:,133])

array([  0, 134], dtype=uint16)

In [15]:
iscell = np.load(roi_dir / 'iscell.npy')
iscell.shape

(134, 2)

In [17]:
merged_masks = np.load(roi_dir / f'merged_masks_{mouse:03}_plane_{plane}_{session:03}.npy',
                       allow_pickle=True).item()

In [18]:
merged_masks.keys()

dict_keys(['meanImg', 'meanImgE', 'max_proj'])

In [20]:
merged_masks['meanImg'].shape

(387, 687, 72)

In [21]:
np.unique(merged_masks['meanImg'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72], dtype=uint16)

In [22]:
np.unique(merged_masks['meanImgE'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81],
      dtype=uint16)

In [23]:
np.unique(merged_masks['max_proj'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95], dtype=uint16)

In [24]:
num_rois = np.load(roi_dir / f'num_rois_{mouse:03}_plane_{plane}_{session:03}.npy')
num_rois

array([[53, 59, 62, 66, 69, 72, 72],
       [63, 71, 75, 78, 79, 81, 81],
       [80, 85, 90, 91, 94, 95, 95]])

In [25]:
num_unique_rois = np.load(roi_dir / f'num_unique_rois_{mouse:03}_plane_{plane}_{session:03}.npy')
num_unique_rois

array([[[ 1,  6],
        [ 2,  3],
        [ 7,  4],
        [ 9,  3],
        [12,  3],
        [15,  0]],

       [[ 6,  8],
        [11,  4],
        [13,  3],
        [20,  1],
        [20,  2],
        [23,  0]],

       [[ 3,  6],
        [ 9,  5],
        [13,  2],
        [20,  3],
        [22,  2],
        [26,  0]]])

# Neuronal signal dataframe

In [27]:
reduced_frame_time = pd.read_pickle(roi_dir / f'reduced_frame_time.pkl')
reduced_frame_time.head()

trialNum  frame_start_time  frame_end_time  trial_duration frame_index
0        2          0.351470        0.383900        4.314105           1
1        2          0.481189        0.513619        4.314105           2
2        2          0.610908        0.643337        4.314105           3
3        2          0.740627        0.773056        4.314105           4
4        2          0.870346        0.902775        4.314105           5

In [28]:
refined_frame_time = pd.read_pickle(roi_dir / f'refined_frame_time.pkl')
refined_frame_time.head()

trialNum  frame_start_time  frame_end_time  trial_duration frame_index  \
0        2          0.351470        0.383900        4.314105           1   
1        2          0.481189        0.513619        4.314105           2   
2        2          0.610908        0.643337        4.314105           3   
3        2          0.740627        0.773056        4.314105           4   
4        2          0.870346        0.902775        4.314105           5   

   remove_frame  remove_trial  
0         False         False  
1         False         False  
2         False         False  
3         False         False  
4         False         False

# Whisker data

In [4]:
whisker_dir = Path(r'E:\TPM\JK\WhiskerVideo')
mouse = 25
session = 3
whisker_session_dir = whisker_dir / f'JK{mouse:03}S{session:02}'
whisker_pkl_fn = f'JK{mouse:03}S{session:02}_whisker.pkl'
whisker_pkl = pd.read_pickle(whisker_session_dir / whisker_pkl_fn)
whisker_pkl.columns

Index(['amplitude', 'arcLength', 'kappaH', 'kappaV', 'midpoint', 'phase',
       'phi', 'poleAngle', 'poleDistance', 'poleMovingFrames', 'polePosition',
       'poleUpFrames', 'protractionSlide', 'protractionSlideByWhisking',
       'protractionTFchunks', 'protractionTFchunksByWhisking',
       'protractionTouchDuration', 'protractionTouchDurationByWhisking',
       'retractionSlide', 'retractionSlideByWhisking', 'retractionTFchunks',
       'retractionTFchunksByWhisking', 'retractionTouchDuration',
       'retractionTouchDurationByWhisking', 'theta', 'whisker_time',
       'whiskingStartFrames', 'mouse_name', 'session_name'],
      dtype='object')

In [5]:
whisker_pkl.index

Int64Index([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
            ...
            368, 369, 370, 371, 372, 373, 374, 375, 376, 377],
           dtype='int64', name='trialNum', length=376)

In [32]:
whisker_pkl.head()

amplitude  \
trialNum                                                      
2         [0.1120494503411022, 0.0773610668341734, 0.047...   
3         [2.663283131286702, 1.2759453714445574, 1.5299...   
4         [1.9925797261745597, 1.7596101535969138, 1.520...   
5         [1.062988934657812, 0.8241170579025188, 0.8353...   
6         [1.3215559856718835, 2.332453952677843, 2.7139...   

                                                  arcLength  \
trialNum                                                      
2         [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
3         [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
4         [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
5         [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   
6         [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...   

                                                     kappaH  \
trialNum                                                      
2         [0.028230989282557278, 0.027747604479175337, 0...   
3         [0.02192368612008598, 0.022401161945715797, 0....   
4         [0.020910858384018523, 0.022415314221942186, 0...   
5         [0.02050759312419506, 0.020693151389785915, 0....   
6         [0.024081165203598157, 0.01909150455145891, 0....   

                                                     kappaV  \
trialNum                                                      
2         [-0.050709654585140436, -0.04912657045486456, ...   
3         [-0.05148633621510797, -0.05179630738114133, -...   
4         [-0.04987775821761756, -0.05243916130685084, -...   
5         [-0.05774239721185456, -0.05447276851004021, -...   
6         [-0.05051955979391675, -0.052321209688238716, ...   

                                                   midpoint  \
trialNum                                                      
2         [-23.242985098222128, -23.243675680549472, -23...   
3         [-10.936527219253362, -11.003985094863797, -11...   
4         [-11.638586362860918, -11.668318024759381, -11...   
5         [-10.980825014950286, -10.810623550762893, -10...   
6         [-6.202850280352959, -6.034399997117823, -5.86...   

                                                      phase  \
trialNum                                                      
2         [-1.428783523782121, -1.689815252745931, -2.37...   
3         [1.6497037362943963, 1.818804190358328, 1.8726...   
4         [1.5389477210649638, 1.4768919925997976, 1.427...   
5         [2.3369688573159113, 2.5074619958064215, 2.388...   
6         [1.4940845109864258, 2.1466234668591246, 2.659...   

                                                        phi  poleAngle  \
trialNum                                                                 
2         [3.6651240340198536, 3.687700830566926, 3.7135...         45   
3         [-4.10917501818044, -4.62078802516819, -4.3054...         45   
4         [0.4164677051680596, 0.34778010269002274, 0.08...        135   
5         [5.5006593781319335, 5.363392207195308, 5.3302...         45   
6         [13.44462735825601, 14.020582298270684, 13.949...         45   

          poleDistance                                   poleMovingFrames  \
trialNum                                                                    
2               140000  [420.0, 421.0, 422.0, 423.0, 424.0, 425.0, 426...   
3               140000  [366.0, 367.0, 368.0, 369.0, 370.0, 371.0, 372...   
4               140000  [356.0, 357.0, 358.0, 359.0, 360.0, 361.0, 362...   
5               140000  [366.0, 367.0, 368.0, 369.0, 370.0, 371.0, 372...   
6               140000  [366.0, 367.0, 368.0, 369.0, 370.0, 371.0, 372...   

          ...                          retractionSlideByWhisking  \
trialNum  ...                                                      
2         ...                                                 []   
3         ...  [[0.0, 0.37717595429835016, 0.5906804256218757...   
4         ...                                                 []   

# Behavior data

In [6]:
behavior_dir = Path(r'E:\TPM\JK\SoloData')
mouse = 25
mouse_dir = behavior_dir / f'JK{mouse:03}'


In [13]:

behavior_data = mat73.loadmat(mouse_dir / f'behavior_JK{mouse:03}_h5.mat')


In [15]:
behavior_data['hb'].keys()

dict_keys(['mouse_name', 'sessions'])

In [21]:
behavior_data['hb']['sessions'][0]['trials'][0].keys()

dict_keys(['answerLickTime', 'answerPeriodTime', 'beamBreakTimesLeft', 'beamBreakTimesRight', 'choice', 'drinkingTime', 'extraITIOnErrorSetting', 'motorApPosition', 'motorDistance', 'poleDownOnsetTime', 'poleUpOnsetTime', 'rewardTimeLeft', 'rewardTimeRight', 'samplingPeriodTime', 'servoAngle', 'trialNum', 'trialType'])

# GLM results

In [24]:
mouse = 25
plane = 1
session = 1
plane_dir = base_dir / f'{mouse:03}/plane_{plane}'
roi_dir = plane_dir / f'{session:03}/plane0/roi'
glm_dir = roi_dir / 'glm' / 'touch_combined'
glm = xr.open_dataset(glm_dir / 'glm_result.nc')

In [25]:
glm

<xarray.Dataset>
Dimensions:             (index: 4106, cell_id: 120, dropped_feature: 5,
                         feature: 58, fold: 5, lambdas: 120)
Coordinates:
  * index               (index) int32 0 1 2 3 4 5 ... 4101 4102 4103 4104 4105
  * cell_id             (cell_id) int32 0 1 2 4 5 7 ... 140 141 142 143 144 145
  * lambdas             (lambdas) float64 432.9 14.85 ... 7.055e+03 7.055e+03
  * feature             (feature) object 'intercept' ... 'first_reward_lick_r...
  * dropped_feature     (dropped_feature) object 'touch' 'whisking' ... 'reward'
  * fold                (fold) object 'fold_0' 'fold_1' ... 'fold_3' 'fold_4'
Data variables:
    predicted_drop      (index, cell_id, dropped_feature) float64 ...
    traces              (index, cell_id) float32 ...
    predicted_final     (index, cell_id) float64 ...
    predicted_fold      (index, cell_id) float64 ...
    X                   (index, feature) float64 ...
    varexp_model_fold   (cell_id, fold) float64 ...
    varexp_drop         (cell_id, dropped_feature) float64 ...
    lambdas_drop        (cell_id, dropped_feature) float64 ...
    varexp_model_final  (cell_id) float64 ...
    W_fold              (feature, cell_id, fold) float64 ...
    W_drop              (feature, cell_id, dropped_feature) float64 ...
    W_final             (feature, cell_id) float64 ...

# Touch / tuning results

In [26]:
tt_dir = roi_dir / 'touch_tuning'
tt = np.load(tt_dir / 'touch_tuning_all.npy', allow_pickle=True).item()

In [28]:
tt.keys()

dict_keys(['touch_response', 'touch_cell_inds', 'tuned_cell_inds', 'ttest_results', 'stat_results'])

In [29]:
tt['touch_response']

<xarray.DataArray (trialNum: 130, cell_index: 120)>
array([[23.697496  ,  3.9965377 , -0.57848024, ..., 18.063412  ,
        -0.56911266, -1.434853  ],
       [ 0.        ,  7.7150245 ,  8.375292  , ...,  0.        ,
         0.3416276 ,  0.30320108],
       [ 0.22470629,  3.6308353 ,  3.637494  , ...,  0.21098846,
        -7.3470163 , -0.5237255 ],
       ...,
       [20.234934  , 10.694776  ,  1.0033797 , ..., 11.484102  ,
         0.        ,  2.29376   ],
       [ 0.39951807,  1.8683989 ,  2.210435  , ...,  0.99462575,
         2.1659508 ,  0.406649  ],
       [-1.1809673 ,  5.969204  , 28.385906  , ...,  1.2207804 ,
        -2.1874409 , -0.27671272]], dtype=float32)
Coordinates:
  * trialNum    (trialNum) int32 2 3 4 5 6 7 8 9 ... 244 245 246 247 248 249 250
  * cell_index  (cell_index) int64 0 1 2 4 5 7 8 ... 139 140 141 142 143 144 145
Attributes:
    touch_window:  all

In [31]:
tt['stat_results']

{'ttest': {0: Ttest_indResult(statistic=0.40759692107513, pvalue=0.6842505262678316),
  1: Ttest_indResult(statistic=6.120111571944617, pvalue=1.0595120643077282e-08),
  2: Ttest_indResult(statistic=10.187194675938914, pvalue=3.2707327689437386e-18),
  4: Ttest_indResult(statistic=0.9447493808338615, pvalue=0.34656676837473466),
  7: Ttest_indResult(statistic=-4.843653702449614, pvalue=3.614166897729458e-06),
  10: Ttest_indResult(statistic=-0.339442723563208, pvalue=0.7348325383418337),
  13: Ttest_indResult(statistic=-2.22429623434205, pvalue=0.027881052353937112),
  14: Ttest_indResult(statistic=-4.325258688171403, pvalue=3.038523807026904e-05),
  15: Ttest_indResult(statistic=-6.04308643840142, pvalue=1.5379594088200015e-08),
  17: Ttest_indResult(statistic=0.37509442718327196, pvalue=0.708211038677459),
  18: Ttest_indResult(statistic=0.08840868380218152, pvalue=0.9296900311193241),
  19: Ttest_indResult(statistic=3.792292037699206, pvalue=0.00022900637574400345),
  22: Ttest_indR